name: gamestory-clean
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - numpy=1.23.5
  - pandas=1.5.3
  - matplotlib=3.5.3
  - plotly=5.14.1
  - scikit-learn=1.1.3
  - xgboost=1.7.4
  - shap=0.41.0
  - statsmodels=0.13.5
  - ipykernel
  - nbformat>=4.2.0
  - pip
